In [19]:
print("Hello World")

Hello World


In [20]:
# import liberaris
import pandas as pd 
import numpy as np 
import pickle 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [21]:
df = pd.read_csv('C:\AI & ML\Customer_Churn.csv')
df.head()

LoyaltyID Customer ID Senior Citizen Partner Dependents  Tenure  \
0     318537  7590-VHVEG             No     Yes         No       1   
1     152148  5575-GNVDE             No      No         No      34   
2     326527  3668-QPYBK             No      No         No       2   
3     845894  7795-CFOCW             No      No         No      45   
4     503388  9237-HQITU             No      No         No       2   

  Phone Service    Multiple Lines Internet Service Online Security  ...  \
0            No  No phone service              DSL              No  ...   
1           Yes                No              DSL             Yes  ...   
2           Yes                No              DSL             Yes  ...   
3            No  No phone service              DSL             Yes  ...   
4           Yes                No      Fiber optic              No  ...   

  Device Protection Tech Support Streaming TV Streaming Movies  \
0                No           No           No               No   
1               Yes           No           No               No   
2                No           No           No               No   
3               Yes          Yes           No               No   
4                No           No           No               No   

         Contract Paperless Billing             Payment Method  \
0  Month-to-month               Yes           Electronic check   
1        One year                No               Mailed check   
2  Month-to-month               Yes               Mailed check   
3        One year                No  Bank transfer (automatic)   
4  Month-to-month               Yes           Electronic check   

  Monthly Charges  Total Charges Churn  
0           29.85          29.85    No  
1           56.95         1889.5    No  
2           53.85         108.15   Yes  
3           42.30        1840.75    No  
4           70.70         151.65   Yes  

[5 rows x 21 columns]

In [22]:
df.drop(columns=['LoyaltyID','Customer ID'] ,inplace=True)

In [23]:
print(df.columns)


Index(['Senior Citizen', 'Partner', 'Dependents', 'Tenure', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn'],
      dtype='object')


In [24]:
df.head(5)

Senior Citizen Partner Dependents  Tenure Phone Service    Multiple Lines  \
0             No     Yes         No       1            No  No phone service   
1             No      No         No      34           Yes                No   
2             No      No         No       2           Yes                No   
3             No      No         No      45            No  No phone service   
4             No      No         No       2           Yes                No   

  Internet Service Online Security Online Backup Device Protection  \
0              DSL              No           Yes                No   
1              DSL             Yes            No               Yes   
2              DSL             Yes           Yes                No   
3              DSL             Yes            No               Yes   
4      Fiber optic              No            No                No   

  Tech Support Streaming TV Streaming Movies        Contract  \
0           No           No               No  Month-to-month   
1           No           No               No        One year   
2           No           No               No  Month-to-month   
3          Yes           No               No        One year   
4           No           No               No  Month-to-month   

  Paperless Billing             Payment Method  Monthly Charges Total Charges  \
0               Yes           Electronic check            29.85         29.85   
1                No               Mailed check            56.95        1889.5   
2               Yes               Mailed check            53.85        108.15   
3                No  Bank transfer (automatic)            42.30       1840.75   
4               Yes           Electronic check            70.70        151.65   

  Churn  
0    No  
1    No  
2   Yes  
3    No  
4   Yes

In [25]:
d={ "Customer ID": "CustomerID","Senior Citizen":"SeniorCitizen",'Phone Service':'PhoneService',
                   'Multiple Lines':'MultipleLines','Internet Service':'InternetService','Online Security':'OnlineSecurity','Online Backup':'OnlineBackup',
                   'Device Protection':'DeviceProtection','Tech Support':'TechSupport', 'Streaming TV': 'StreamingTV', 'Streaming Movies': 'StreamingMovies',
                   'Paperless Billing':'PaperlessBilling','Payment Method':'PaymentMethod','Monthly Charges':'MonthlyCharges','Total Charges':'TotalCharges'}

df.rename(columns=d, inplace=True)

In [26]:
df.head(5)

SeniorCitizen Partner Dependents  Tenure PhoneService     MultipleLines  \
0            No     Yes         No       1           No  No phone service   
1            No      No         No      34          Yes                No   
2            No      No         No       2          Yes                No   
3            No      No         No      45           No  No phone service   
4            No      No         No       2          Yes                No   

  InternetService OnlineSecurity OnlineBackup DeviceProtection TechSupport  \
0             DSL             No          Yes               No          No   
1             DSL            Yes           No              Yes          No   
2             DSL            Yes          Yes               No          No   
3             DSL            Yes           No              Yes         Yes   
4     Fiber optic             No           No               No          No   

  StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No              No  Month-to-month              Yes   
1          No              No        One year               No   
2          No              No  Month-to-month              Yes   
3          No              No        One year               No   
4          No              No  Month-to-month              Yes   

               PaymentMethod  MonthlyCharges TotalCharges Churn  
0           Electronic check           29.85        29.85    No  
1               Mailed check           56.95       1889.5    No  
2               Mailed check           53.85       108.15   Yes  
3  Bank transfer (automatic)           42.30      1840.75    No  
4           Electronic check           70.70       151.65   Yes

In [27]:
df.isna().sum()

SeniorCitizen       0
Partner             0
Dependents          0
Tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [28]:
print(df.columns)


Index(['SeniorCitizen', 'Partner', 'Dependents', 'Tenure', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges',
       'TotalCharges', 'Churn'],
      dtype='object')


In [29]:
le = LabelEncoder()
df['SeniorCitizen'] = le.fit_transform(df['SeniorCitizen'])
df['Partner'] = le.fit_transform(df['Partner'])
df['Dependents'] = le.fit_transform(df['Dependents'])
df['PhoneService'] = le.fit_transform(df['PhoneService'])
df['MultipleLines'] = le.fit_transform(df['MultipleLines'])
df['InternetService'] = le.fit_transform(df['InternetService'])
df['OnlineSecurity'] = le.fit_transform(df['OnlineSecurity'])
df['OnlineBackup'] = le.fit_transform(df['OnlineBackup'])
df['DeviceProtection'] = le.fit_transform(df['DeviceProtection'])
df['TechSupport'] = le.fit_transform(df['TechSupport'])
df['StreamingTV'] = le.fit_transform(df['StreamingTV'])
df['StreamingMovies'] = le.fit_transform(df['StreamingMovies'])
df['Contract'] = le.fit_transform(df['Contract'])
df['PaperlessBilling'] = le.fit_transform(df['PaperlessBilling'])
df['PaymentMethod'] = le.fit_transform(df['PaymentMethod'])
df['Churn'] = le.fit_transform(df['Churn'])

In [30]:
df.head(5)

SeniorCitizen  Partner  Dependents  Tenure  PhoneService  MultipleLines  \
0              0        1           0       1             0              1   
1              0        0           0      34             1              0   
2              0        0           0       2             1              0   
3              0        0           0      45             0              1   
4              0        0           0       2             1              0   

   InternetService  OnlineSecurity  OnlineBackup  DeviceProtection  \
0                0               0             2                 0   
1                0               2             0                 2   
2                0               2             2                 0   
3                0               2             0                 2   
4                1               0             0                 0   

   TechSupport  StreamingTV  StreamingMovies  Contract  PaperlessBilling  \
0            0            0                0         0                 1   
1            0            0                0         1                 0   
2            0            0                0         0                 1   
3            2            0                0         1                 0   
4            0            0                0         0                 1   

   PaymentMethod  MonthlyCharges TotalCharges  Churn  
0              2           29.85        29.85      0  
1              3           56.95       1889.5      0  
2              3           53.85       108.15      1  
3              0           42.30      1840.75      0  
4              2           70.70       151.65      1

In [31]:
df['PaymentMethod'].unique()

array([2, 3, 0, 1])

In [32]:
ss =StandardScaler()
df[['Tenure','MonthlyCharges','TotalCharges']] =ss.fit_transform(df[['Tenure','MonthlyCharges','TotalCharges']])
df.head(10)

ValueError: could not convert string to float: ' '

In [33]:
print(df[['Tenure', 'MonthlyCharges', 'TotalCharges']].info())
print(df[['Tenure', 'MonthlyCharges', 'TotalCharges']].head())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Tenure          7043 non-null   int64  
 1   MonthlyCharges  7043 non-null   float64
 2   TotalCharges    7043 non-null   object 
dtypes: float64(1), int64(1), object(1)
memory usage: 165.2+ KB
None
   Tenure  MonthlyCharges TotalCharges
0       1           29.85        29.85
1      34           56.95       1889.5
2       2           53.85       108.15
3      45           42.30      1840.75
4       2           70.70       151.65


In [34]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
print(df['TotalCharges'].isnull().sum())



11


In [35]:
df['TotalCharges'] = df['TotalCharges'].fillna(df['TotalCharges'].mean())



In [36]:
df.dropna(subset=['TotalCharges'], inplace=True)


In [37]:
ss = StandardScaler()
df[['Tenure', 'MonthlyCharges', 'TotalCharges']] = ss.fit_transform(df[['Tenure', 'MonthlyCharges', 'TotalCharges']])
df.head()

SeniorCitizen  Partner  Dependents    Tenure  PhoneService  MultipleLines  \
0              0        1           0 -1.277445             0              1   
1              0        0           0  0.066327             1              0   
2              0        0           0 -1.236724             1              0   
3              0        0           0  0.514251             0              1   
4              0        0           0 -1.236724             1              0   

   InternetService  OnlineSecurity  OnlineBackup  DeviceProtection  \
0                0               0             2                 0   
1                0               2             0                 2   
2                0               2             2                 0   
3                0               2             0                 2   
4                1               0             0                 0   

   TechSupport  StreamingTV  StreamingMovies  Contract  PaperlessBilling  \
0            0            0                0         0                 1   
1            0            0                0         1                 0   
2            0            0                0         0                 1   
3            2            0                0         1                 0   
4            0            0                0         0                 1   

   PaymentMethod  MonthlyCharges  TotalCharges  Churn  
0              2       -1.160323     -0.994971      0  
1              3       -0.259629     -0.173876      0  
2              3       -0.362660     -0.960399      1  
3              0       -0.746535     -0.195400      0  
4              2        0.197365     -0.941193      1

In [38]:
#seprate dataset into taining and testing split 
selected_columns = [
    'SeniorCitizen', 'Partner', 'Dependents', 'Tenure',
    'PhoneService', 'MultipleLines', 'InternetService',
    'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
    'TechSupport', 'StreamingTV', 'StreamingMovies',
    'Contract', 'PaperlessBilling', 'PaymentMethod',
    'MonthlyCharges', 'TotalCharges'
]

# Filter the dataset
X = df[selected_columns]
y = df['Churn']


In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [40]:
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [41]:
y_predict = model.predict(X_test)
print(y_predict)

[1 0 0 ... 0 1 0]


In [42]:
#importing accuracy data 
from sklearn.metrics import accuracy_score,confusion_matrix
 

In [43]:
print(accuracy_score(y_test, y_predict))

0.8121154756270705


In [44]:
print(confusion_matrix(y_test, y_predict))

[[1389  150]
 [ 247  327]]


In [45]:
model_dt = DecisionTreeClassifier()
model_dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [47]:
y_dt_predict = model.predict(X_test)
print(y_dt_predict)

[1 0 0 ... 0 1 0]


In [48]:
print(accuracy_score(y_test, y_dt_predict))

0.8121154756270705


In [49]:
print(confusion_matrix(y_test, y_dt_predict))

[[1389  150]
 [ 247  327]]


In [51]:
model_rf = RandomForestClassifier()
model_rf.fit(X_train,y_train)

RandomForestClassifier()

In [52]:
y_rf_predict = model.predict(X_test)
print(y_rf_predict)

[1 0 0 ... 0 1 0]


In [53]:
print(accuracy_score(y_test, y_rf_predict))

0.8121154756270705


In [54]:
print(confusion_matrix(y_test, y_rf_predict))

[[1389  150]
 [ 247  327]]


In [55]:
with open('C:\AI & ML\Task3\Churning_model.pkl','wb') as f:
    pickle.dump(model,f)